// Catppuccin Mocha - Pastel palette on deep navy background
export default {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'cdd6f4', background: '1e1e2e' },
    { token: 'comment', foreground: '6c7086', fontStyle: 'italic' },
    { token: 'comment.line', foreground: '6c7086', fontStyle: 'italic' },
    { token: 'comment.block', foreground: '6c7086', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'cba6f7' },
    { token: 'keyword.control', foreground: 'cba6f7' },
    { token: 'keyword.operator', foreground: '94e2d5' },
    { token: 'keyword.other', foreground: 'cba6f7' },
    { token: 'string', foreground: 'a6e3a1' },
    { token: 'string.escape', foreground: 'f5c2e7' },
    { token: 'number', foreground: 'fab387' },
    { token: 'constant', foreground: 'fab387' },
    { token: 'constant.language', foreground: 'fab387' },
    { token: 'variable', foreground: 'cdd6f4' },
    { token: 'variable.parameter', foreground: 'eba0ac', fontStyle: 'italic' },
    { token: 'type', foreground: 'f9e2af', fontStyle: 'italic' },
    { token: 'type.identifier', foreground: 'f9e2af', fontStyle: 'italic' },
    { token: 'class', foreground: 'f9e2af', fontStyle: 'italic' },
    { token: 'interface', foreground: 'f9e2af', fontStyle: 'italic' },
    { token: 'enum', foreground: 'f9e2af', fontStyle: 'italic' },
    { token: 'function', foreground: '89b4fa' },
    { token: 'function.call', foreground: '89b4fa' },
    { token: 'method', foreground: '89b4fa' },
    { token: 'storage', foreground: 'cba6f7' },
    { token: 'storage.type', foreground: 'cba6f7' },
    { token: 'storage.modifier', foreground: 'cba6f7' },
    { token: 'support', foreground: '89b4fa' },
    { token: 'support.function', foreground: '89b4fa' },
    { token: 'support.type', foreground: 'f9e2af' },
    { token: 'tag', foreground: '89b4fa' },
    { token: 'attribute.name', foreground: 'f9e2af' },
    { token: 'attribute.value', foreground: 'a6e3a1' },
    { token: 'delimiter', foreground: '9399b2' },
    { token: 'delimiter.bracket', foreground: '9399b2' },
    { token: 'operator', foreground: '94e2d5' },
    { token: 'meta', foreground: 'cdd6f4' },
    { token: 'meta.tag', foreground: '89b4fa' },
    { token: 'invalid', foreground: 'f38ba8', fontStyle: 'underline' },
  ],
  colors: {
    'editor.foreground': '#cdd6f4',
    'editor.background': '#1e1e2e',
    'editor.selectionBackground': '#9399b240',
    'editor.lineHighlightBackground': '#cdd6f412',
    'editorCursor.foreground': '#f5e0dc',
    'editorWhitespace.foreground': '#9399b266',
    'editorIndentGuide.background': '#45475a',
    'editorIndentGuide.activeBackground': '#585b70',
    'editor.selectionHighlightBackground': '#9399b233',
    'editor.wordHighlightBackground': '#9399b233',
    'editor.findMatchBackground': '#5e3f53',
    'editor.findMatchHighlightBackground': '#3e5767',
    'editorLineNumber.foreground': '#7f849c',
    'editorLineNumber.activeForeground': '#cba6f7',
    'editorBracketMatch.background': '#9399b21a',
    'editorBracketMatch.border': '#9399b2',
    'editorGutter.background': '#1e1e2e',
  },
};
