// Dracula Theme - The iconic dark theme with purple accents
export default {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'f8f8f2', background: '282a36' },
    { token: 'comment', foreground: '6272a4', fontStyle: 'italic' },
    { token: 'comment.line', foreground: '6272a4', fontStyle: 'italic' },
    { token: 'comment.block', foreground: '6272a4', fontStyle: 'italic' },
    { token: 'comment.documentation', foreground: '6272a4', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'ff79c6' },
    { token: 'keyword.control', foreground: 'ff79c6' },
    { token: 'keyword.operator', foreground: 'ff79c6' },
    { token: 'keyword.other', foreground: 'ff79c6' },
    { token: 'string', foreground: 'f1fa8c' },
    { token: 'string.escape', foreground: 'ff79c6' },
    { token: 'string.regexp', foreground: 'ff5555' },
    { token: 'number', foreground: 'bd93f9' },
    { token: 'number.hex', foreground: 'bd93f9' },
    { token: 'number.float', foreground: 'bd93f9' },
    { token: 'constant', foreground: 'bd93f9' },
    { token: 'constant.language', foreground: 'bd93f9' },
    { token: 'constant.numeric', foreground: 'bd93f9' },
    { token: 'variable', foreground: 'f8f8f2' },
    { token: 'variable.parameter', foreground: 'ffb86c' },
    { token: 'variable.other', foreground: 'f8f8f2' },
    { token: 'type', foreground: '8be9fd', fontStyle: 'italic' },
    { token: 'type.identifier', foreground: '8be9fd', fontStyle: 'italic' },
    { token: 'class', foreground: '8be9fd' },
    { token: 'interface', foreground: '8be9fd' },
    { token: 'enum', foreground: '8be9fd' },
    { token: 'function', foreground: '50fa7b' },
    { token: 'function.call', foreground: '50fa7b' },
    { token: 'method', foreground: '50fa7b' },
    { token: 'storage', foreground: 'ff79c6' },
    { token: 'storage.type', foreground: '8be9fd', fontStyle: 'italic' },
    { token: 'storage.modifier', foreground: 'ff79c6' },
    { token: 'support', foreground: '8be9fd' },
    { token: 'support.function', foreground: '50fa7b' },
    { token: 'support.type', foreground: '8be9fd' },
    { token: 'tag', foreground: 'ff79c6' },
    { token: 'attribute.name', foreground: '50fa7b' },
    { token: 'attribute.value', foreground: 'f1fa8c' },
    { token: 'delimiter', foreground: 'f8f8f2' },
    { token: 'delimiter.bracket', foreground: 'f8f8f2' },
    { token: 'operator', foreground: 'ff79c6' },
    { token: 'invalid', foreground: 'ff5555', fontStyle: 'underline' },
    { token: 'meta', foreground: 'f8f8f2' },
    { token: 'meta.tag', foreground: 'ff79c6' },
  ],
  colors: {
    'editor.foreground': '#f8f8f2',
    'editor.background': '#282a36',
    'editor.selectionBackground': '#44475a',
    'editor.lineHighlightBackground': '#44475a50',
    'editorCursor.foreground': '#f8f8f2',
    'editorWhitespace.foreground': '#44475a',
    'editorIndentGuide.background': '#44475a',
    'editorIndentGuide.activeBackground': '#6272a4',
    'editor.selectionHighlightBackground': '#424450',
    'editor.wordHighlightBackground': '#8be9fd50',
    'editor.findMatchBackground': '#ffb86c80',
    'editor.findMatchHighlightBackground': '#ffb86c40',
    'editorLineNumber.foreground': '#6272a4',
    'editorLineNumber.activeForeground': '#f8f8f2',
    'editorBracketMatch.background': '#44475a',
    'editorBracketMatch.border': '#bd93f9',
    'editorGutter.background': '#282a36',
  },
};
