// Light Plus Theme - Based on VS Code default light theme
export default {
  base: 'vs',
  inherit: true,
  rules: [
    { token: '', foreground: '000000', background: 'ffffff' },
    { token: 'comment', foreground: '008000' },
    { token: 'comment.line', foreground: '008000' },
    { token: 'comment.block', foreground: '008000' },
    { token: 'comment.documentation', foreground: '008000' },
    { token: 'keyword', foreground: '0000ff' },
    { token: 'keyword.control', foreground: 'af00db' },
    { token: 'keyword.operator', foreground: '0000ff' },
    { token: 'keyword.other', foreground: '0000ff' },
    { token: 'string', foreground: 'a31515' },
    { token: 'string.escape', foreground: 'ee0000' },
    { token: 'string.regexp', foreground: '811f3f' },
    { token: 'number', foreground: '098658' },
    { token: 'number.hex', foreground: '098658' },
    { token: 'number.float', foreground: '098658' },
    { token: 'constant', foreground: '0000ff' },
    { token: 'constant.language', foreground: '0000ff' },
    { token: 'constant.numeric', foreground: '098658' },
    { token: 'variable', foreground: '001080' },
    { token: 'variable.parameter', foreground: '001080' },
    { token: 'variable.other', foreground: '001080' },
    { token: 'type', foreground: '267f99' },
    { token: 'type.identifier', foreground: '267f99' },
    { token: 'class', foreground: '267f99' },
    { token: 'interface', foreground: '267f99' },
    { token: 'enum', foreground: '267f99' },
    { token: 'function', foreground: '795e26' },
    { token: 'function.call', foreground: '795e26' },
    { token: 'method', foreground: '795e26' },
    { token: 'storage', foreground: '0000ff' },
    { token: 'storage.type', foreground: '0000ff' },
    { token: 'storage.modifier', foreground: '0000ff' },
    { token: 'support', foreground: '267f99' },
    { token: 'support.function', foreground: '795e26' },
    { token: 'support.type', foreground: '267f99' },
    { token: 'tag', foreground: '800000' },
    { token: 'attribute.name', foreground: 'ff0000' },
    { token: 'attribute.value', foreground: '0000ff' },
    { token: 'delimiter', foreground: '000000' },
    { token: 'delimiter.bracket', foreground: '000000' },
    { token: 'operator', foreground: '000000' },
    { token: 'invalid', foreground: 'cd3131' },
    { token: 'meta', foreground: '000000' },
    { token: 'meta.tag', foreground: '800000' },
  ],
  colors: {
    'editor.foreground': '#000000',
    'editor.background': '#ffffff',
    'editor.selectionBackground': '#add6ff',
    'editor.lineHighlightBackground': '#f8f8f8',
    'editorCursor.foreground': '#000000',
    'editorWhitespace.foreground': '#d3d3d3',
    'editorIndentGuide.background': '#d3d3d3',
    'editorIndentGuide.activeBackground': '#939393',
    'editor.selectionHighlightBackground': '#add6ff80',
    'editor.wordHighlightBackground': '#d7d7d7',
    'editor.findMatchBackground': '#ffff00',
    'editor.findMatchHighlightBackground': '#ffff0066',
    'editorLineNumber.foreground': '#237893',
    'editorLineNumber.activeForeground': '#0b216f',
    'editorBracketMatch.background': '#bad0f8',
    'editorBracketMatch.border': '#c9c9c9',
    'editorGutter.background': '#ffffff',
  },
};
