// Monokai Theme - Classic hacker aesthetic with neon colors
export default {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'f8f8f2', background: '272822' },
    { token: 'comment', foreground: '75715e', fontStyle: 'italic' },
    { token: 'comment.line', foreground: '75715e', fontStyle: 'italic' },
    { token: 'comment.block', foreground: '75715e', fontStyle: 'italic' },
    { token: 'comment.documentation', foreground: '75715e', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'f92672' },
    { token: 'keyword.control', foreground: 'f92672' },
    { token: 'keyword.operator', foreground: 'f92672' },
    { token: 'keyword.other', foreground: 'f92672' },
    { token: 'string', foreground: 'e6db74' },
    { token: 'string.escape', foreground: 'ae81ff' },
    { token: 'string.regexp', foreground: 'e6db74' },
    { token: 'number', foreground: 'ae81ff' },
    { token: 'number.hex', foreground: 'ae81ff' },
    { token: 'number.float', foreground: 'ae81ff' },
    { token: 'constant', foreground: 'ae81ff' },
    { token: 'constant.language', foreground: 'ae81ff' },
    { token: 'constant.numeric', foreground: 'ae81ff' },
    { token: 'variable', foreground: 'f8f8f2' },
    { token: 'variable.parameter', foreground: 'fd971f', fontStyle: 'italic' },
    { token: 'variable.other', foreground: 'f8f8f2' },
    { token: 'type', foreground: '66d9ef', fontStyle: 'italic' },
    { token: 'type.identifier', foreground: '66d9ef', fontStyle: 'italic' },
    { token: 'class', foreground: 'a6e22e', fontStyle: 'underline' },
    { token: 'interface', foreground: '66d9ef', fontStyle: 'italic' },
    { token: 'enum', foreground: '66d9ef' },
    { token: 'function', foreground: 'a6e22e' },
    { token: 'function.call', foreground: 'a6e22e' },
    { token: 'method', foreground: 'a6e22e' },
    { token: 'storage', foreground: 'f92672' },
    { token: 'storage.type', foreground: '66d9ef', fontStyle: 'italic' },
    { token: 'storage.modifier', foreground: 'f92672' },
    { token: 'support', foreground: '66d9ef' },
    { token: 'support.function', foreground: '66d9ef' },
    { token: 'support.type', foreground: '66d9ef' },
    { token: 'tag', foreground: 'f92672' },
    { token: 'attribute.name', foreground: 'a6e22e' },
    { token: 'attribute.value', foreground: 'e6db74' },
    { token: 'delimiter', foreground: 'f8f8f2' },
    { token: 'delimiter.bracket', foreground: 'f8f8f2' },
    { token: 'operator', foreground: 'f92672' },
    { token: 'invalid', foreground: 'f44747', fontStyle: 'underline' },
    { token: 'meta', foreground: 'f8f8f2' },
    { token: 'meta.tag', foreground: 'f92672' },
  ],
  colors: {
    'editor.foreground': '#f8f8f2',
    'editor.background': '#272822',
    'editor.selectionBackground': '#49483e',
    'editor.lineHighlightBackground': '#3e3d32',
    'editorCursor.foreground': '#f8f8f2',
    'editorWhitespace.foreground': '#464741',
    'editorIndentGuide.background': '#464741',
    'editorIndentGuide.activeBackground': '#75715e',
    'editor.selectionHighlightBackground': '#49483e50',
    'editor.wordHighlightBackground': '#a6e22e30',
    'editor.findMatchBackground': '#e6db7480',
    'editor.findMatchHighlightBackground': '#e6db7440',
    'editorLineNumber.foreground': '#90908a',
    'editorLineNumber.activeForeground': '#f8f8f2',
    'editorBracketMatch.background': '#4e4d4380',
    'editorBracketMatch.border': '#75715e',
    'editorGutter.background': '#272822',
  },
};
