// Nightmare - Tokyo cyberpunk night palette, tuned for long-session readability
export default {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'ffffff', background: '070812' },
    { token: 'comment', foreground: '6c63ff', fontStyle: 'italic' },
    { token: 'comment.line', foreground: '6c63ff', fontStyle: 'italic' },
    { token: 'comment.block', foreground: '6c63ff', fontStyle: 'italic' },

    { token: 'keyword', foreground: 'ff00ff' },
    { token: 'keyword.control', foreground: 'ff00ff' },
    { token: 'keyword.control.conditional', foreground: 'ff00ff' },
    { token: 'keyword.control.loop', foreground: 'ff00ff' },
    { token: 'keyword.control.flow', foreground: 'ff00ff' },
    { token: 'keyword.control.return', foreground: 'ff00ff' },
    { token: 'storage', foreground: 'ff00ff' },
    { token: 'storage.type', foreground: 'ff00ff' },
    { token: 'storage.modifier', foreground: 'ff00ff' },
    { token: 'type', foreground: 'ff00ff' },
    { token: 'type.identifier', foreground: 'ff00ff' },
    { token: 'class', foreground: 'ff00ff' },
    { token: 'interface', foreground: 'ff00ff' },
    { token: 'struct', foreground: 'ff00ff' },
    { token: 'enum', foreground: 'ff00ff' },

    { token: 'function', foreground: '00f7ff' },
    { token: 'function.call', foreground: '00f7ff' },
    { token: 'method', foreground: '00f7ff' },
    { token: 'support.function', foreground: '00f7ff' },

    { token: 'keyword.operator', foreground: 'e0e0ff' },
    { token: 'operator', foreground: 'e0e0ff' },
    { token: 'delimiter', foreground: 'e0e0ff' },
    { token: 'delimiter.bracket', foreground: 'e0e0ff' },

    { token: 'variable', foreground: 'ffffff' },
    { token: 'variable.parameter', foreground: 'ffffff' },
    { token: 'identifier', foreground: 'ffffff' },

    { token: 'string', foreground: '39ff14' },
    { token: 'string.escape', foreground: '39ff14' },

    { token: 'number', foreground: 'ff9f1c' },
    { token: 'constant', foreground: 'ff9f1c' },
    { token: 'constant.numeric', foreground: 'ff9f1c' },
    { token: 'constant.language', foreground: 'ff9f1c' },

    { token: 'tag', foreground: '00f7ff' },
    { token: 'attribute.name', foreground: 'ff00ff' },
    { token: 'attribute.value', foreground: '39ff14' },
    { token: 'invalid', foreground: 'ff637d', fontStyle: 'underline' },
  ],
  colors: {
    'editor.foreground': '#ffffff',
    'editor.background': '#070812',
    'editor.selectionBackground': '#6c63ff40',
    'editor.lineHighlightBackground': '#1a213340',
    'editorCursor.foreground': '#00f7ff',
    'editorWhitespace.foreground': '#2d3554',
    'editorIndentGuide.background': '#1f2944',
    'editorIndentGuide.activeBackground': '#38527d',
    'editor.selectionHighlightBackground': '#8578ff2a',
    'editor.wordHighlightBackground': '#ff00ff22',
    'editor.wordHighlightStrongBackground': '#00f7ff2b',
    'editor.findMatchBackground': '#ff00ff5c',
    'editor.findMatchHighlightBackground': '#00f7ff49',
    'editorLineNumber.foreground': '#4f5f82',
    'editorLineNumber.activeForeground': '#c9d6ff',
    'editorBracketMatch.background': '#232f4d',
    'editorBracketMatch.border': '#00f7ff',
    'editorGutter.background': '#070812',
    'editorGutter.modifiedBackground': '#00f7ff',
    'editorGutter.addedBackground': '#39ff14',
    'editorGutter.deletedBackground': '#ff5b86',
  },
};
