// Night Owl Theme - Optimized for night coding with artistic colors
export default {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'd6deeb', background: '011627' },
    { token: 'comment', foreground: '637777', fontStyle: 'italic' },
    { token: 'comment.line', foreground: '637777', fontStyle: 'italic' },
    { token: 'comment.block', foreground: '637777', fontStyle: 'italic' },
    { token: 'comment.documentation', foreground: '637777', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'c792ea', fontStyle: 'italic' },
    { token: 'keyword.control', foreground: 'c792ea', fontStyle: 'italic' },
    { token: 'keyword.operator', foreground: '7fdbca' },
    { token: 'keyword.other', foreground: 'c792ea' },
    { token: 'string', foreground: 'ecc48d' },
    { token: 'string.escape', foreground: 'f78c6c' },
    { token: 'string.regexp', foreground: '80cbc4' },
    { token: 'number', foreground: 'f78c6c' },
    { token: 'number.hex', foreground: 'f78c6c' },
    { token: 'number.float', foreground: 'f78c6c' },
    { token: 'constant', foreground: '82aaff' },
    { token: 'constant.language', foreground: 'ff5874' },
    { token: 'constant.numeric', foreground: 'f78c6c' },
    { token: 'variable', foreground: 'd6deeb' },
    { token: 'variable.parameter', foreground: 'd7dbe0' },
    { token: 'variable.other', foreground: 'd6deeb' },
    { token: 'type', foreground: 'ffcb8b' },
    { token: 'type.identifier', foreground: 'ffcb8b' },
    { token: 'class', foreground: 'ffcb8b' },
    { token: 'interface', foreground: 'ffcb8b' },
    { token: 'enum', foreground: 'ffcb8b' },
    { token: 'function', foreground: '82aaff' },
    { token: 'function.call', foreground: '82aaff' },
    { token: 'method', foreground: '82aaff' },
    { token: 'storage', foreground: 'c792ea' },
    { token: 'storage.type', foreground: 'c792ea', fontStyle: 'italic' },
    { token: 'storage.modifier', foreground: 'c792ea' },
    { token: 'support', foreground: 'addb67' },
    { token: 'support.function', foreground: '82aaff' },
    { token: 'support.type', foreground: 'ffcb8b' },
    { token: 'tag', foreground: 'caece6' },
    { token: 'attribute.name', foreground: 'addb67' },
    { token: 'attribute.value', foreground: 'ecc48d' },
    { token: 'delimiter', foreground: 'd6deeb' },
    { token: 'delimiter.bracket', foreground: 'd9f5dd' },
    { token: 'operator', foreground: '7fdbca' },
    { token: 'invalid', foreground: 'ef5350', fontStyle: 'underline' },
    { token: 'meta', foreground: 'd6deeb' },
    { token: 'meta.tag', foreground: 'caece6' },
  ],
  colors: {
    'editor.foreground': '#d6deeb',
    'editor.background': '#011627',
    'editor.selectionBackground': '#1d3b53',
    'editor.lineHighlightBackground': '#0b2942',
    'editorCursor.foreground': '#80a4c2',
    'editorWhitespace.foreground': '#2e4960',
    'editorIndentGuide.background': '#1e3a56',
    'editorIndentGuide.activeBackground': '#5c99d6',
    'editor.selectionHighlightBackground': '#1d3b5370',
    'editor.wordHighlightBackground': '#82aaff30',
    'editor.findMatchBackground': '#ecc48d50',
    'editor.findMatchHighlightBackground': '#addb6740',
    'editorLineNumber.foreground': '#4b6479',
    'editorLineNumber.activeForeground': '#c5e4fd',
    'editorBracketMatch.background': '#0b3954',
    'editorBracketMatch.border': '#82aaff',
    'editorGutter.background': '#011627',
  },
};
