// Nightmare - Tokyo cyberpunk night palette, tuned for long-session readability
export default {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'f5f5ff', background: '05070d' },
    { token: 'comment', foreground: '5f6cff', fontStyle: 'italic' },
    { token: 'comment.line', foreground: '5f6cff', fontStyle: 'italic' },
    { token: 'comment.block', foreground: '5f6cff', fontStyle: 'italic' },

    { token: 'keyword', foreground: 'ff00ff' },
    { token: 'keyword.control', foreground: 'ff00ff' },
    { token: 'keyword.control.conditional', foreground: 'ff00ff' },
    { token: 'keyword.control.loop', foreground: 'ff00ff' },
    { token: 'keyword.control.flow', foreground: 'ff00ff' },
    { token: 'keyword.control.return', foreground: 'ff00ff' },
    { token: 'storage', foreground: 'ff00ff' },
    { token: 'storage.type', foreground: 'ff00ff' },
    { token: 'storage.modifier', foreground: 'ff00ff' },
    { token: 'type', foreground: 'ff00ff' },
    { token: 'type.identifier', foreground: 'ff00ff' },
    { token: 'class', foreground: 'ff00ff' },
    { token: 'interface', foreground: 'ff00ff' },
    { token: 'struct', foreground: 'ff00ff' },
    { token: 'enum', foreground: 'ff00ff' },

    { token: 'function', foreground: '00f7ff' },
    { token: 'function.call', foreground: '00f7ff' },
    { token: 'method', foreground: '00f7ff' },
    { token: 'support.function', foreground: '00f7ff' },

    { token: 'keyword.operator', foreground: 'ffffff' },
    { token: 'operator', foreground: 'ffffff' },
    { token: 'delimiter', foreground: 'ffffff' },
    { token: 'delimiter.bracket', foreground: 'ffffff' },

    { token: 'variable', foreground: 'f5f5ff' },
    { token: 'variable.parameter', foreground: 'f5f5ff' },
    { token: 'identifier', foreground: 'f5f5ff' },

    { token: 'string', foreground: '39ff14' },
    { token: 'string.escape', foreground: '39ff14' },

    { token: 'number', foreground: 'ff9f1c' },
    { token: 'constant', foreground: 'ff9f1c' },
    { token: 'constant.numeric', foreground: 'ff9f1c' },
    { token: 'constant.language', foreground: 'ff9f1c' },

    { token: 'tag', foreground: '00f7ff' },
    { token: 'attribute.name', foreground: 'ff00ff' },
    { token: 'attribute.value', foreground: '39ff14' },
    { token: 'invalid', foreground: 'ff637d', fontStyle: 'underline' },
  ],
  colors: {
    'editor.foreground': '#f5f5ff',
    'editor.background': '#05070d',
    'editor.selectionBackground': '#7b5cff4d',
    'editor.lineHighlightBackground': '#141b2f47',
    'editorCursor.foreground': '#00f7ff',
    'editorWhitespace.foreground': '#29314f',
    'editorIndentGuide.background': '#1a2138',
    'editorIndentGuide.activeBackground': '#375174',
    'editor.selectionHighlightBackground': '#8661ff30',
    'editor.wordHighlightBackground': '#ff00ff26',
    'editor.wordHighlightStrongBackground': '#00f7ff33',
    'editor.findMatchBackground': '#ff00ff66',
    'editor.findMatchHighlightBackground': '#00f7ff55',
    'editorLineNumber.foreground': '#4a5679',
    'editorLineNumber.activeForeground': '#dce5ff',
    'editorBracketMatch.background': '#202947',
    'editorBracketMatch.border': '#00f7ff',
    'editorGutter.background': '#05070d',
    'editorGutter.modifiedBackground': '#00f7ff',
    'editorGutter.addedBackground': '#39ff14',
    'editorGutter.deletedBackground': '#ff5b86',
  },
};
