// One Dark Pro Theme - Modern and clean, inspired by Atom
export default {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'abb2bf', background: '282c34' },
    { token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
    { token: 'comment.line', foreground: '5c6370', fontStyle: 'italic' },
    { token: 'comment.block', foreground: '5c6370', fontStyle: 'italic' },
    { token: 'comment.documentation', foreground: '5c6370', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'c678dd' },
    { token: 'keyword.control', foreground: 'c678dd' },
    { token: 'keyword.operator', foreground: 'c678dd' },
    { token: 'keyword.other', foreground: 'c678dd' },
    { token: 'string', foreground: '98c379' },
    { token: 'string.escape', foreground: '56b6c2' },
    { token: 'string.regexp', foreground: '56b6c2' },
    { token: 'number', foreground: 'd19a66' },
    { token: 'number.hex', foreground: 'd19a66' },
    { token: 'number.float', foreground: 'd19a66' },
    { token: 'constant', foreground: 'd19a66' },
    { token: 'constant.language', foreground: 'd19a66' },
    { token: 'constant.numeric', foreground: 'd19a66' },
    { token: 'variable', foreground: 'e06c75' },
    { token: 'variable.parameter', foreground: 'e06c75' },
    { token: 'variable.other', foreground: 'e06c75' },
    { token: 'type', foreground: 'e5c07b' },
    { token: 'type.identifier', foreground: 'e5c07b' },
    { token: 'class', foreground: 'e5c07b' },
    { token: 'interface', foreground: 'e5c07b' },
    { token: 'enum', foreground: 'e5c07b' },
    { token: 'function', foreground: '61afef' },
    { token: 'function.call', foreground: '61afef' },
    { token: 'method', foreground: '61afef' },
    { token: 'storage', foreground: 'c678dd' },
    { token: 'storage.type', foreground: 'c678dd' },
    { token: 'storage.modifier', foreground: 'c678dd' },
    { token: 'support', foreground: '56b6c2' },
    { token: 'support.function', foreground: '61afef' },
    { token: 'support.type', foreground: 'e5c07b' },
    { token: 'tag', foreground: 'e06c75' },
    { token: 'attribute.name', foreground: 'd19a66' },
    { token: 'attribute.value', foreground: '98c379' },
    { token: 'delimiter', foreground: 'abb2bf' },
    { token: 'delimiter.bracket', foreground: 'abb2bf' },
    { token: 'operator', foreground: '56b6c2' },
    { token: 'invalid', foreground: 'e06c75', fontStyle: 'underline' },
    { token: 'meta', foreground: 'abb2bf' },
    { token: 'meta.tag', foreground: 'e06c75' },
  ],
  colors: {
    'editor.foreground': '#abb2bf',
    'editor.background': '#282c34',
    'editor.selectionBackground': '#3e4451',
    'editor.lineHighlightBackground': '#2c313a',
    'editorCursor.foreground': '#528bff',
    'editorWhitespace.foreground': '#3b4048',
    'editorIndentGuide.background': '#3b4048',
    'editorIndentGuide.activeBackground': '#5c6370',
    'editor.selectionHighlightBackground': '#3e445170',
    'editor.wordHighlightBackground': '#61afef30',
    'editor.findMatchBackground': '#d19a6680',
    'editor.findMatchHighlightBackground': '#61afef40',
    'editorLineNumber.foreground': '#4b5263',
    'editorLineNumber.activeForeground': '#abb2bf',
    'editorBracketMatch.background': '#515a6b',
    'editorBracketMatch.border': '#528bff',
    'editorGutter.background': '#282c34',
  },
};
