// SynthWave '84 Theme - Retro-futuristic with neon glow aesthetic
export default {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'f0e5e5', background: '262335' },
    { token: 'comment', foreground: '848bbd', fontStyle: 'italic' },
    { token: 'comment.line', foreground: '848bbd', fontStyle: 'italic' },
    { token: 'comment.block', foreground: '848bbd', fontStyle: 'italic' },
    { token: 'comment.documentation', foreground: '848bbd', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'fede5d' },
    { token: 'keyword.control', foreground: 'ff7edb' },
    { token: 'keyword.operator', foreground: 'ff7edb' },
    { token: 'keyword.other', foreground: 'fede5d' },
    { token: 'string', foreground: 'ff8b39' },
    { token: 'string.escape', foreground: 'f97e72' },
    { token: 'string.regexp', foreground: '72f1b8' },
    { token: 'number', foreground: 'f97e72' },
    { token: 'number.hex', foreground: 'f97e72' },
    { token: 'number.float', foreground: 'f97e72' },
    { token: 'constant', foreground: 'f97e72' },
    { token: 'constant.language', foreground: 'ff7edb' },
    { token: 'constant.numeric', foreground: 'f97e72' },
    { token: 'variable', foreground: 'ff7edb' },
    { token: 'variable.parameter', foreground: 'fe4450' },
    { token: 'variable.other', foreground: 'ff7edb' },
    { token: 'type', foreground: 'fe4450' },
    { token: 'type.identifier', foreground: 'fe4450' },
    { token: 'class', foreground: 'fe4450' },
    { token: 'interface', foreground: 'fe4450' },
    { token: 'enum', foreground: 'fe4450' },
    { token: 'function', foreground: '36f9f6' },
    { token: 'function.call', foreground: '36f9f6' },
    { token: 'method', foreground: '36f9f6' },
    { token: 'storage', foreground: 'fede5d' },
    { token: 'storage.type', foreground: 'fede5d' },
    { token: 'storage.modifier', foreground: 'ff7edb' },
    { token: 'support', foreground: '72f1b8' },
    { token: 'support.function', foreground: '36f9f6' },
    { token: 'support.type', foreground: 'fe4450' },
    { token: 'tag', foreground: 'ff7edb' },
    { token: 'attribute.name', foreground: '72f1b8' },
    { token: 'attribute.value', foreground: 'ff8b39' },
    { token: 'delimiter', foreground: 'f0e5e5' },
    { token: 'delimiter.bracket', foreground: 'fede5d' },
    { token: 'operator', foreground: 'ff7edb' },
    { token: 'invalid', foreground: 'fe4450', fontStyle: 'underline' },
    { token: 'meta', foreground: 'f0e5e5' },
    { token: 'meta.tag', foreground: 'ff7edb' },
  ],
  colors: {
    'editor.foreground': '#f0e5e5',
    'editor.background': '#262335',
    'editor.selectionBackground': '#463465',
    'editor.lineHighlightBackground': '#34294f',
    'editorCursor.foreground': '#ff7edb',
    'editorWhitespace.foreground': '#3c3258',
    'editorIndentGuide.background': '#3c3258',
    'editorIndentGuide.activeBackground': '#ff7edb40',
    'editor.selectionHighlightBackground': '#46346570',
    'editor.wordHighlightBackground': '#36f9f630',
    'editor.findMatchBackground': '#fede5d80',
    'editor.findMatchHighlightBackground': '#ff7edb40',
    'editorLineNumber.foreground': '#6e6591',
    'editorLineNumber.activeForeground': '#ff7edb',
    'editorBracketMatch.background': '#463465',
    'editorBracketMatch.border': '#ff7edb',
    'editorGutter.background': '#262335',
  },
};
