// Whalio Hyperwave - High-contrast neon palette for long coding sessions
export default {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'f4ecff', background: '120321' },
    { token: 'comment', foreground: '6c7086', fontStyle: 'italic' },
    { token: 'comment.line', foreground: '6c7086', fontStyle: 'italic' },
    { token: 'comment.block', foreground: '6c7086', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'cba6f7' },
    { token: 'keyword.control', foreground: 'cba6f7' },
    { token: 'keyword.control.conditional', foreground: 'cba6f7' },
    { token: 'keyword.control.loop', foreground: 'cba6f7' },
    { token: 'keyword.control.flow', foreground: 'cba6f7' },
    { token: 'keyword.control.return', foreground: 'cba6f7' },
    { token: 'storage', foreground: 'cba6f7' },
    { token: 'storage.type', foreground: 'cba6f7' },
    { token: 'storage.modifier', foreground: 'cba6f7' },
    { token: 'function', foreground: '89b4fa' },
    { token: 'function.call', foreground: '89b4fa' },
    { token: 'method', foreground: '89b4fa' },
    { token: 'support.function', foreground: '89b4fa' },
    { token: 'keyword.operator', foreground: '89b4fa' },
    { token: 'operator', foreground: '89b4fa' },
    { token: 'delimiter', foreground: '89b4fa' },
    { token: 'delimiter.bracket', foreground: '89b4fa' },
    { token: 'type', foreground: 'f9e2af' },
    { token: 'type.identifier', foreground: 'f9e2af' },
    { token: 'class', foreground: 'f9e2af' },
    { token: 'interface', foreground: 'f9e2af' },
    { token: 'struct', foreground: 'f9e2af' },
    { token: 'enum', foreground: 'f9e2af' },
    { token: 'support.type', foreground: 'f9e2af' },
    { token: 'variable', foreground: 'f4ecff' },
    { token: 'variable.parameter', foreground: 'ffb3ff', fontStyle: 'italic' },
    { token: 'string', foreground: '78ffb3' },
    { token: 'string.escape', foreground: '00ffff' },
    { token: 'number', foreground: 'ffff00' },
    { token: 'constant', foreground: 'ffff00' },
    { token: 'constant.numeric', foreground: 'ffff00' },
    { token: 'constant.language', foreground: 'ffff00' },
    { token: 'meta.preprocessor', foreground: 'ff00ff' },
    { token: 'keyword.control.directive', foreground: 'ff00ff' },
    { token: 'tag', foreground: '00ffff' },
    { token: 'attribute.name', foreground: 'ffff00' },
    { token: 'attribute.value', foreground: '78ffb3' },
    { token: 'invalid', foreground: 'ff5bd1', fontStyle: 'underline' },
  ],
  colors: {
    'editor.foreground': '#f4ecff',
    'editor.background': '#120321',
    'editor.selectionBackground': '#3b82f666',
    'editor.lineHighlightBackground': '#ffffff08',
    'editorCursor.foreground': '#ffff00',
    'editorWhitespace.foreground': '#5e4b73',
    'editorIndentGuide.background': '#2a1940',
    'editorIndentGuide.activeBackground': '#00ffff66',
    'editor.selectionHighlightBackground': '#00ffff22',
    'editor.wordHighlightBackground': '#ff00ff26',
    'editor.findMatchBackground': '#ff00ff55',
    'editor.findMatchHighlightBackground': '#00ffff3d',
    'editorLineNumber.foreground': '#6c7086',
    'editorLineNumber.activeForeground': '#00ffff',
    'editorBracketMatch.background': '#2a1940',
    'editorBracketMatch.border': '#00ffff',
    'editorGutter.background': '#120321',
  },
};
